apiVersion: berg.norelect.ch/v1
kind: Ctf
metadata:
  name: demo-ctf
  namespace: default
spec:
  start: "1970-01-01T00:00:00+00:00"
  end: "1980-01-01T00:00:00+00:00"
  scoring:
    maximumScore: 500
    minimalScore: 100
    solvesBeforeMinimum: 45
    teams: false
    freezeStart: "2040-01-01T00:00:00+00:00"
    freezeEnd: "2050-01-01T00:00:00+00:00"
    playerCategories:
      - name: junior
        description: Junior
      - name: senior
        description: Senior
    rateLimits:
      maxInvalidFlagSubmissionsPerDay: 25
      maxInvalidFlagSubmissionsPerHour: 10
      maxInvalidFlagSubmissionsPerMinute: 5
---
apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  name: nginx
  namespace: default
spec:
  ctf: demo-ctf
  author: NoRelect
  flag: flag{test_flag}
  description: nginx
  difficulty: baby
  categories:
    - web
    - misc
  containers:
    - hostname: nginx
      image: nginx:latest
      ports:
        - port: 80
          protocol: tcp
          appProtocol: http
          type: publicVHost
---
apiVersion: berg.norelect.ch/v1
kind: Ctf
metadata:
  name: old-ctf
  namespace: default
spec:
  start: "1970-01-01T00:00:00+00:00"
  end: "2050-01-01T00:00:00+00:00"
  scoring:
    maximumScore: 500
    minimalScore: 100
    solvesBeforeMinimum: 45
    teams: false
    freezeStart: "2040-01-01T00:00:00+00:00"
    freezeEnd: "2050-01-01T00:00:00+00:00"
    playerCategories:
      - name: junior
        description: Junior
      - name: senior
        description: Senior
    rateLimits:
      maxInvalidFlagSubmissionsPerDay: 25
      maxInvalidFlagSubmissionsPerHour: 10
      maxInvalidFlagSubmissionsPerMinute: 5
---
apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  name: old-nginx
  namespace: default
spec:
  ctf: old-ctf
  author: NoRelect
  flag: flag{test_flag}
  description: nginx
  difficulty: baby
  categories:
    - web
    - misc
  containers:
    - hostname: nginx
      image: nginx:latest
      ports:
        - port: 80
          protocol: tcp
          appProtocol: http
          type: publicVHost
