{{- if .Values.berg.createConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "berg.fullname" . }}-appsettings
  labels:
    {{- include "berg.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {{ .Values.berg.logLevel | toJson }}
      },
      "AllowedHosts": {{ .Values.berg.domain | quote }},
      "ConnectionStrings": {
        "BergDbConnection": "Host={{ .Values.berg.postgresql.host }}; Database={{ .Values.berg.postgresql.database }}; Username={{ .Values.berg.postgresql.username }}; Password={{ .Values.berg.postgresql.password }};"
      },
      "infra": {
        "challengeDomain": {{ .Values.gateway.domain | quote }},
        "platformDomain": {{ .Values.berg.domain | quote }},
        "gatewayName": {{ .Values.gateway.name | quote }},
        "gatewayNamespace": {{ .Values.gateway.namespace | quote }},
        "challengeHttpPort": {{ .Values.gateway.httpRoutePort }},
        "challengeTlsPort": {{ .Values.gateway.tlsRoutePort }},
        "challengeHttpListenerName": {{ .Values.gateway.httpRouteListenerName | quote }},
        "challengeTlsListenerName": {{ .Values.gateway.tlsRouteListenerName | quote }},
        "playerIdNamespace": {{ .Values.berg.playerIdNamespace | quote }},
        "redirectUris": {{ .Values.berg.redirectUris | toJson }},
        "pullSecretName": {{ .Values.berg.pullSecretName | quote }},
        "challengeImagePullPolicy": {{ .Values.berg.challengeImagePullPolicy | quote }},
        "challengeInstanceTimeout": {{ .Values.berg.challengeInstanceTimeout | quote }},
        {{- if .Values.berg.challengeRuntimeClassName }}
        "challengeRuntimeClassName": {{ .Values.berg.challengeRuntimeClassName | quote }},
        {{- end }}
        "challengeEgressBandwidth": {{ .Values.berg.challengeEgressBandwidth | quote }},
        {{- if .Values.handout.enabled }}
        "handoutServiceUrl": "http://{{ include "berg.fullname" . }}-handout",
        {{- end }}
        "openTelemetryGrpcTracingEndpoint": {{ .Values.berg.openTelemetry.grpc.tracingEndpoint | toJson }},
        "openTelemetryGrpcMetricsEndpoint": {{ .Values.berg.openTelemetry.grpc.metricsEndpoint | toJson }},
        "openTelemetryGrpcLoggingEndpoint": {{ .Values.berg.openTelemetry.grpc.loggingEndpoint | toJson }},
        "useKubernetesSecretKeyProvider": true,
      },
      "discord": {{ .Values.berg.discord | toJson }},
      "genericOpenId": {{ .Values.berg.genericOpenId | toJson }},
      "ctf": {{ .Values.berg.ctf | toJson }}
    }
{{- end }}