---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "berg.fullname" . }}-api
  labels:
    {{- include "berg.labels" . | nindent 4 }}
    component: api
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      {{- include "berg.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      labels:
        {{- include "berg.selectorLabels" . | nindent 8 }}
        component: api
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.berg.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.berg.pullSecretName }}
      {{- end }}
      serviceAccountName: {{ include "berg.fullname" . }}
      containers:
        - name: berg-api
          image: "{{ .Values.berg.image.repository }}:{{ .Values.berg.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.berg.image.imagePullPolicy }}
          env:
            - name: "ASPNETCORE_URLS"
              value: "http://0.0.0.0:8080"
            - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
              value: "true"
          {{- if .Values.berg.postgresql.existingSecret.name }}
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.berg.postgresql.existingSecret.name | quote }}
                  key: {{ .Values.berg.postgresql.existingSecret.hostKey | quote }}
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.berg.postgresql.existingSecret.name | quote }}
                  key: {{ .Values.berg.postgresql.existingSecret.portKey | quote }}
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.berg.postgresql.existingSecret.name | quote }}
                  key: {{ .Values.berg.postgresql.existingSecret.databaseKey | quote }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.berg.postgresql.existingSecret.name | quote }}
                  key: {{ .Values.berg.postgresql.existingSecret.usernameKey | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.berg.postgresql.existingSecret.name | quote }}
                  key: {{ .Values.berg.postgresql.existingSecret.passwordKey | quote }}
          {{- end }}
          {{- with .Values.berg.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.berg.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: appsettings
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          resources:
            {{- toYaml .Values.berg.resources | nindent 12 }}
      volumes:
        - name: appsettings
          configMap:
            name: {{ include "berg.fullname" . }}-appsettings
{{ if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "berg.fullname" . }}-frontend
  labels:
    {{- include "berg.labels" . | nindent 4 }}
    component: frontend
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      {{- include "berg.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "berg.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      {{ if .Values.frontend.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.frontend.pullSecretName }}
      {{ end }}
      containers:
        - name: berg-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.imagePullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{ end }}
{{ if .Values.handout.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "berg.fullname" . }}-handout
  labels:
    {{- include "berg.labels" . | nindent 4 }}
    component: handout
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      {{- include "berg.selectorLabels" . | nindent 6 }}
      component: handout
  template:
    metadata:
      labels:
        {{- include "berg.selectorLabels" . | nindent 8 }}
        component: handout
    spec:
      {{ if .Values.handout.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.handout.pullSecretName }}
      {{ end }}
      containers:
        - name: berg-handout
          image: "{{ .Values.handout.image.repository }}:{{ .Values.handout.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.handout.image.imagePullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.handout.resources | nindent 12 }}
{{ end }}
