---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect
spec:
  parentRefs:
  - name: {{ include "berg.fullname" . }}-gateway
    sectionName: http-redirect
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "berg.fullname" . }}-gateway
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName | quote }}
  listeners:
  - name: http-redirect
    protocol: HTTP
    port: {{ .Values.gateway.httpPort }}
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: berg
  - name: http-chall
    protocol: HTTPS
    port: {{ .Values.gateway.httpPort }}
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: {{ .Values.gateway.tlsSecretName | quote }}
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            app.kubernetes.io/managed-by: berg
            app.kubernetes.io/component: challenge
  - name: tls-chall
    protocol: TLS
    port: {{ .Values.gateway.tlsPort }}
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: {{ .Values.gateway.tlsSecretName | quote }}
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            app.kubernetes.io/managed-by: berg
            app.kubernetes.io/component: challenge
