---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "berg.fullname" . }}-role
  labels:
    {{- include "berg.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch"]
  resourceNames:
    - "berg-openid"
    - "berg-protect"
    {{- if .Values.berg.pullSecretName }}
    - {{ .Values.berg.pullSecretName | quote }}
    {{- end }}
- apiGroups: ["berg.norelect.ch"]
  resources: ["challenges", "pages"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["berg.norelect.ch"]
  resources: ["challengeinstances"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "berg.fullname" . }}-role-binding
  labels:
    {{- include "berg.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "berg.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "berg.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
