---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "berg.fullname" . }}-api
  labels:
    {{- include "berg.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    {{- include "berg.selectorLabels" . | nindent 4 }}
    component: api
{{ if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "berg.fullname" . }}-frontend
  labels:
    {{- include "berg.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    {{- include "berg.selectorLabels" . | nindent 4 }}
    component: frontend
{{ end }}
{{ if .Values.handout.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "berg.fullname" . }}-handout
  labels:
    {{- include "berg.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    {{- include "berg.selectorLabels" . | nindent 4 }}
    component: handout
{{ end }}
