---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "berg.fullname" . }}-api
  labels:
    {{- include "berg.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    {{- include "berg.selectorLabels" . | nindent 4 }}
    component: api
