version: '3'
services:
  berg:
    image: berg:latest
    build: .
    ports:
      - "5000:80"
    volumes:
      - "./Berg/ctf.json:/app/ctf.json:ro"
      - "./Berg/kubeconfig.yaml:/app/kubeconfig.yaml:ro"
      - "./Berg/appsettings.Development.json:/app/appsettings.json:ro"
