version: '3'
services:
  berg-challenge-server:
    image: berg-challenge-server:latest
    build:
      context: .
      dockerfile: Berg.ChallengeServer/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "KUBECONFIG=/app/kube-config.yaml"
    ports:
      - "127.0.0.1:5000:80"
    volumes:
      - "./Berg.ChallengeServer/kube-config.yaml:/app/kube-config.yaml:ro"
      - "./Berg.ChallengeServer/appsettings.Development.json:/app/appsettings.json:ro"
