version: '3'
services:
  berg-challenge-server:
    image: berg-challenge-server:latest
    build:
      context: .
      dockerfile: Berg.ChallengeServer/Dockerfile
    environment:
      - "ASPNETCORE_URLS=http://0.0.0.0:5000"
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "KUBECONFIG=/app/kube-config.yaml"
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - "./Berg.ChallengeServer/kube-config.yaml:/app/kube-config.yaml:ro"
      - "./Berg.ChallengeServer/appsettings.Development.json:/app/appsettings.json:ro"

#  berg:
#    image: berg:latest
#    build:
#      context: .
#      dockerfile: Berg/Dockerfile
#    ports:
#      - "5000:80"
#    volumes:
#      - "./Berg/ctf.json:/app/ctf.json:ro"
#      - "./Berg/kubeconfig.yaml:/app/kubeconfig.yaml:ro"
#      - "./Berg/appsettings.Development.json:/app/appsettings.json:ro"
#
#  berg-discord-integration:
#    image: berg-discord-integration:latest
#    build:
#      context: .
#      dockerfile: Berg.DiscordIntegration/Dockerfile
#    volumes:
#      - "./Berg.DiscordIntegration/appsettings.Development.json:/app/appsettings.json:ro"
