---
site_name: Berg CTF Platform
site_url: https://bergctf.github.io/platform

repo_name: BergCTF/platform
repo_url: https://github.com/BergCTF/platform
edit_uri: https://github.com/BergCTF/platform/edit/main/docs

copyright: "&copy; 2026 NoRelect"

theme:
  name: material
  logo: "logo.png"
  favicon: logo.png
  logo: logo.png
  icon:
    tag:
      default: lucide/hash
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/sun
        name: Switch to light mode
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji # (1)!
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg


nav:
  - Home: index.md
  - Guides:
      - Getting started: getting-started.md
      - Developing Challenges: challenge.md
      - Adding attachments: attachments.md
      - OIDC Configuration: oidc.md
      - Production Deployment: production.md
  - Reference: 
    - Helm chart: helm.md
  - Integrations:
    - Discord: discord.md
    - Observability: metrics.md
