---
apiVersion: v2
name: berg
description: Deploy berg using helm!
type: application
version: 0.0.0
appVersion: "0.0.0"
sources:
  - https://github.com/NoRelect/berg
dependencies:
  - name: postgresql
    version: ~13.2.16
    repository: oci://registry-1.docker.io/bitnamicharts
