---
nameOverride: ""
fullnameOverride: ""

gateway:
  domain: ""
  name: "default-gateway"
  namespace: "default"
  httpListenerName: "http"
  httpsPort: 443
  httpsListenerName: "https"
  httpRoutePort: 1337
  httpRouteRedirectListenerName: "http-chall"
  httpRouteListenerName: "https-chall"
  tlsRoutePort: 31337
  tlsRouteListenerName: "tls-chall"

frontend:
  enabled: true
  pullSecretName: ""
  image:
    repository: "ghcr.io/norelect/berg/frontend"
    imagePullPolicy: IfNotPresent
    tag: ""
  resources:
    limits:
      cpu: "1"
      memory: "500Mi"
    requests:
      cpu: "0.2"
      memory: "100Mi"

handout:
  enabled: false
  pullSecretName: ""
  image:
    repository: "ghcr.io/norelect/berg/handouts"
    imagePullPolicy: IfNotPresent
    tag: ""
  resources:
    limits:
      cpu: "1"
      memory: "500Mi"
    requests:
      cpu: "0.2"
      memory: "100Mi"

berg:
  # additional env vars to add to the berg api server instance
  extraEnv: []
  # additional env vars from secrets or configmaps
  extraEnvFrom: []
  domain: ""
  image:
    repository: "ghcr.io/norelect/berg/api"
    imagePullPolicy: IfNotPresent
    tag: ""
  pullSecretName: ""
  challengeImagePullPolicy: "Always"
  # By default, all challenges will be terminated after 2h
  challengeInstanceTimeout: "0.02:00:00"
  logLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
    Microsoft.EntityFrameworkCore.Database: Warning
    OpenIddict: Warning
    Quartz: Warning
    System.Net.Http.HttpClient.OpenIddict: Warning
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "0.2"
      memory: "100Mi"
  postgresql:
    host: ""
    database: ""
    username: ""
    password: ""
  playerIdNamespace: "00000000-0000-0000-0000-000000000000"
  discord:
    clientId: ""
    clientSecret: ""
    botToken: ""
    notificationGuildId: "0"
    notificationChannelId: "0"
    playerGuildId: "0"
    playerRoleId: "0"
    authorGuildId: "0"
    authorRoleId: "0"
    adminGuildId: "0"
    adminRoleId: "0"
  genericOpenId:
    issuer: ""
    internalIssuer: ""
    clientId: ""
    clientSecret: ""
    scopes: []
    # - "profile"
    # - "email"
    claims:
      id: "sub"
      name: "name"
      email: "email"
  openTelemetry:
    grpc:
      tracingEndpoint: null
      metricsEndpoint: null
      loggingEndpoint: null
  redirectUris: []
  # - "https://frontend.example.com/callback"
  ctf:
    eventName: "Berg CTF"
    eventOrganiser: "Berg Contributors"
    eventLogoUrl: ""
    start: "1970-01-01T00:00:00+00:00"
    end: "2099-01-01T00:00:00+00:00"
    allowAnonymousAccess: true
    teams: false
    playerAttributes: []
    # - name: category
    #   title: Category
    #   description: Select your player category.
    #   public: true
    #   required: true
    #   values:
    #     - value: junior
    #       title: Junior
    #       description: People between the age of 14 and 20.
    #     - value: senior
    #       title: Senior
    #       description: People between the age of 21 and 25.
    #     - value: open
    #       title: Open
    #       description: People over the age of 25.
    scoring:
      freezeStart: "2099-01-01T00:00:00+00:00"
      freezeEnd: "2099-01-01T00:00:00+00:00"
      numSolvesBeforeMinimum: 50

pages:
  home:
    path: /
    title: Home
    index: 0
    content: |
      Welcome to your berg installation!
