apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  name: lost-pass
spec:
  description: |
    Looks like somebody lost his password.
    Can you help me <b>recover</b> it?
  flag: shc2023{ducks_like_2_sleep_quack}
  hosting: private
  containers:
    - name: lost-pass
      image: ghcr.io/swisshackingchallenge/web/lost_pass:latest
      ports:
        - port: 5000
          protocol: tcp
          app_protocol: http
          exposed: true
  attachments:
    - filename: lost_pass.zip
      url: /download/web/lost_pass.zip
