---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: handouts
  namespace: berg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handouts
  template:
    metadata:
      labels:
        app: handouts
    spec:
      imagePullSecrets:
        - name: berg-pull-secret
      containers:
        - name: handouts
          image: ghcr.io/swisshackingchallenge/shc2023-finals/handouts:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "0.1"
              memory: "10Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: handouts
  namespace: berg
spec:
  selector:
    app: handouts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80