---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: berg-ingress
  namespace: berg
spec:
  rules:
  - host: ctf.k8s.personal.horizon.lan
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: berg-challenge-server
            port:
              number: 80
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: berg-challenge-server
            port:
              number: 80
      - path: /download
        pathType: Prefix
        backend:
          service:
            name: handouts
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: berg-frontend
            port:
              number: 80