// <auto-generated />
using System;
using Berg.ChallengeServer.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Berg.ChallengeServer.Migrations
{
    [DbContext(typeof(BergDbContext))]
    partial class BergDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Berg.ChallengeServer.Db.Challenge", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCategoryId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.PlayerCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayerCategories");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.Solve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChallengeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SolvedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Solves");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChallengeName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeName");

                    b.HasIndex("PlayerId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.Player", b =>
                {
                    b.HasOne("Berg.ChallengeServer.Db.PlayerCategory", "PlayerCategory")
                        .WithMany("Players")
                        .HasForeignKey("PlayerCategoryId");

                    b.HasOne("Berg.ChallengeServer.Db.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("PlayerCategory");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.Solve", b =>
                {
                    b.HasOne("Berg.ChallengeServer.Db.Challenge", "Challenge")
                        .WithMany("Solves")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Berg.ChallengeServer.Db.Player", "Player")
                        .WithMany("Solves")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.Submission", b =>
                {
                    b.HasOne("Berg.ChallengeServer.Db.Challenge", "Challenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeName");

                    b.HasOne("Berg.ChallengeServer.Db.Player", "Player")
                        .WithMany("Submissions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.Challenge", b =>
                {
                    b.Navigation("Solves");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.Player", b =>
                {
                    b.Navigation("Solves");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.PlayerCategory", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Berg.ChallengeServer.Db.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
