---
name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      id-token: none
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Berg API
        id: berg-api-docker
        uses: docker/build-push-action@v7
        with:
          context: backend
          file: backend/Berg.Api/Dockerfile

      - name: Build Berg Frontend
        id: berg-frontend-docker
        uses: docker/build-push-action@v7
        with:
          context: frontend
          file: frontend/Dockerfile
